// Generated by gencpp from file actuator/ActivateActuatorResponse.msg
// DO NOT EDIT!


#ifndef ACTUATOR_MESSAGE_ACTIVATEACTUATORRESPONSE_H
#define ACTUATOR_MESSAGE_ACTIVATEACTUATORRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace actuator
{
template <class ContainerAllocator>
struct ActivateActuatorResponse_
{
  typedef ActivateActuatorResponse_<ContainerAllocator> Type;

  ActivateActuatorResponse_()
    {
    }
  ActivateActuatorResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::actuator::ActivateActuatorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::actuator::ActivateActuatorResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ActivateActuatorResponse_

typedef ::actuator::ActivateActuatorResponse_<std::allocator<void> > ActivateActuatorResponse;

typedef boost::shared_ptr< ::actuator::ActivateActuatorResponse > ActivateActuatorResponsePtr;
typedef boost::shared_ptr< ::actuator::ActivateActuatorResponse const> ActivateActuatorResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::actuator::ActivateActuatorResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::actuator::ActivateActuatorResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace actuator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::actuator::ActivateActuatorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actuator::ActivateActuatorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actuator::ActivateActuatorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actuator::ActivateActuatorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actuator::ActivateActuatorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actuator::ActivateActuatorResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::actuator::ActivateActuatorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::actuator::ActivateActuatorResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::actuator::ActivateActuatorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "actuator/ActivateActuatorResponse";
  }

  static const char* value(const ::actuator::ActivateActuatorResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::actuator::ActivateActuatorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::actuator::ActivateActuatorResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::actuator::ActivateActuatorResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActivateActuatorResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::actuator::ActivateActuatorResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::actuator::ActivateActuatorResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ACTUATOR_MESSAGE_ACTIVATEACTUATORRESPONSE_H
