// Generated by gencpp from file darknet_multiplexer_msgs/DarknetCamerasResponse.msg
// DO NOT EDIT!


#ifndef DARKNET_MULTIPLEXER_MSGS_MESSAGE_DARKNETCAMERASRESPONSE_H
#define DARKNET_MULTIPLEXER_MSGS_MESSAGE_DARKNETCAMERASRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace darknet_multiplexer_msgs
{
template <class ContainerAllocator>
struct DarknetCamerasResponse_
{
  typedef DarknetCamerasResponse_<ContainerAllocator> Type;

  DarknetCamerasResponse_()
    : success(false)  {
    }
  DarknetCamerasResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::darknet_multiplexer_msgs::DarknetCamerasResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::darknet_multiplexer_msgs::DarknetCamerasResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DarknetCamerasResponse_

typedef ::darknet_multiplexer_msgs::DarknetCamerasResponse_<std::allocator<void> > DarknetCamerasResponse;

typedef boost::shared_ptr< ::darknet_multiplexer_msgs::DarknetCamerasResponse > DarknetCamerasResponsePtr;
typedef boost::shared_ptr< ::darknet_multiplexer_msgs::DarknetCamerasResponse const> DarknetCamerasResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::darknet_multiplexer_msgs::DarknetCamerasResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::darknet_multiplexer_msgs::DarknetCamerasResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::darknet_multiplexer_msgs::DarknetCamerasResponse_<ContainerAllocator1> & lhs, const ::darknet_multiplexer_msgs::DarknetCamerasResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::darknet_multiplexer_msgs::DarknetCamerasResponse_<ContainerAllocator1> & lhs, const ::darknet_multiplexer_msgs::DarknetCamerasResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace darknet_multiplexer_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::darknet_multiplexer_msgs::DarknetCamerasResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::darknet_multiplexer_msgs::DarknetCamerasResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::darknet_multiplexer_msgs::DarknetCamerasResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::darknet_multiplexer_msgs::DarknetCamerasResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::darknet_multiplexer_msgs::DarknetCamerasResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::darknet_multiplexer_msgs::DarknetCamerasResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::darknet_multiplexer_msgs::DarknetCamerasResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::darknet_multiplexer_msgs::DarknetCamerasResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::darknet_multiplexer_msgs::DarknetCamerasResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "darknet_multiplexer_msgs/DarknetCamerasResponse";
  }

  static const char* value(const ::darknet_multiplexer_msgs::DarknetCamerasResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::darknet_multiplexer_msgs::DarknetCamerasResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::darknet_multiplexer_msgs::DarknetCamerasResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::darknet_multiplexer_msgs::DarknetCamerasResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DarknetCamerasResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::darknet_multiplexer_msgs::DarknetCamerasResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::darknet_multiplexer_msgs::DarknetCamerasResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DARKNET_MULTIPLEXER_MSGS_MESSAGE_DARKNETCAMERASRESPONSE_H
